### ISSUE TITLE
Host at github

### ISSUE THREAD

**Issue by mmikhasenko** [Democratizing-Models-Project/ModelVisualization#1]
Add `.github/workflow/Pages.yml` for hosting the webpage at github.

See last block in the example [here](https://github.com/mmikhasenko/ReactionAmplitudeExamples.jl/blob/main/.github/workflows/pages.yaml)

**Comment by amikhasenko** [comment]
Fixed in [commit](https://github.com/Democratizing-Models-Project/ModelVisualization/commit/10463f92907109941ab0b0a2eeb87a809a912fe3)
